#map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 2.5
raytrace_range: 3.0

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

#footprint: 0.13
#footprint_padding: 0.1
robot_radius: 0.13
plugins:
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  observation_sources: scan
  scan: {sensor_frame: base_scan,
         data_type: LaserScan,
         topic: /scan,
         marking: true,
         clearing: true,
         min_obstacle_height: -2.0,
         max_obstacle_height: 2.0,
         obstacle_range: 2.5, raytrace_range: 3.0}

inflation_layer:
 inflation_radius: 0.13